//! Turning a `StarterKit` into one commit on the visitor's own GitHub account
//! (#40).
//!
//! This module owns the *orchestration* — which calls happen, in which order,
//! and how one file becomes one commit — over whatever [`GitHubApi`] it is
//! given. It knows nothing about HTTP routes, cookies or sessions; that is
//! `github_routes`'s job. The split is what lets `push_kit` below be tested
//! with a fake and no running server at all.

use std::sync::Arc;

use crate::github_api::{GitHubApi, GitHubApiError};
use crate::github_token_store::GithubTokenStore;
use crate::kit::StarterKit;

/// The message every push carries. A constant, not a per-push choice: the
/// commit's *content* is what identifies it, and a visitor comparing two
/// downloads benefits more from a predictable message than a creative one.
const COMMIT_MESSAGE: &str = "Generated by the authkestra playground";

/// The branch the new commit is published under. GitHub's own default for a
/// repository created today, so a browser opening the result lands somewhere
/// ordinary rather than on a branch nothing points at yet.
const DEFAULT_BRANCH: &str = "main";

/// What a successful push hands back to the route handler.
#[derive(Debug, Clone)]
pub struct PushOutcome {
    pub owner: String,
    pub repo: String,
    pub html_url: String,
    pub default_branch: String,
    pub commit_sha: String,
}

/// The GitHub client and the short-lived token store the push routes share,
/// bundled so `AppState` grows one field instead of two.
pub struct GithubPushState {
    pub api: Arc<dyn GitHubApi>,
    pub tokens: GithubTokenStore,
}

impl GithubPushState {
    pub fn new(api: Arc<dyn GitHubApi>, tokens: GithubTokenStore) -> Self {
        Self { api, tokens }
    }
}

/// Create the repository and push the kit's files to it as one commit.
///
/// Uses the Git Data API rather than the Contents API precisely so this is
/// **one commit for the whole kit**, not one commit per file: a blob per
/// file, one tree over all of them, one commit with no parents (the
/// repository is created empty), then a `refs/heads/main` pointed at it.
///
/// `token` is taken by reference and never placed on `self` or in a tracing
/// field — see `github_api`'s module docs for why that matters here.
#[tracing::instrument(skip_all, fields(repo = %repo_name, files = kit.files.len()))]
pub async fn push_kit(
    api: &dyn GitHubApi,
    token: &str,
    repo_name: &str,
    description: Option<&str>,
    kit: &StarterKit,
) -> Result<PushOutcome, GitHubApiError> {
    let repo = api.create_repo(token, repo_name, description).await?;

    // Read back explicitly rather than trusting `owner` embedded in the
    // create-repo response: every subsequent call addresses the repository as
    // `{owner}/{repo}`, and reading the authenticated login is the same
    // one round trip the issue's design calls for.
    let owner = api.current_user(token).await?;

    // One blob per generated file, in the kit's own emission order — which is
    // itself deterministic (`kit::Plan` guarantees it), so two pushes of the
    // same configuration produce byte-identical trees.
    let mut entries = Vec::with_capacity(kit.files.len());
    for file in &kit.files {
        let sha = api
            .create_blob(token, &owner, &repo.name, &file.contents)
            .await?;
        entries.push((file.path.clone(), sha));
    }

    let tree_sha = api.create_tree(token, &owner, &repo.name, &entries).await?;

    // No `parents`: the repository was created with `auto_init: false`, so
    // this commit is the project's first, not a continuation of one GitHub
    // seeded on its own.
    let commit_sha = api
        .create_commit(token, &owner, &repo.name, COMMIT_MESSAGE, &tree_sha)
        .await?;

    api.create_ref(token, &owner, &repo.name, DEFAULT_BRANCH, &commit_sha)
        .await?;

    Ok(PushOutcome {
        owner,
        repo: repo.name,
        html_url: repo.html_url,
        default_branch: repo.default_branch,
        commit_sha,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::kit::GeneratedFile;
    use crate::testing::FakeGitHubApi;

    fn kit_with(files: &[(&str, &str)]) -> StarterKit {
        StarterKit {
            files: files
                .iter()
                .map(|(path, contents)| GeneratedFile {
                    path: path.to_string(),
                    contents: contents.to_string(),
                })
                .collect(),
            slug: "test".to_string(),
        }
    }

    /// The mapping this whole module exists for: every generated file becomes
    /// exactly one blob, and the tree references it at the same path — no
    /// file dropped, none duplicated, none silently reordered.
    #[tokio::test]
    async fn every_kit_file_becomes_one_blob_at_its_own_path() {
        let fake = FakeGitHubApi::default();
        let kit = kit_with(&[
            ("Cargo.toml", "contents-a"),
            ("src/main.rs", "contents-b"),
            ("README.md", "contents-c"),
        ]);

        let outcome = push_kit(&fake, "tok", "my-repo", None, &kit)
            .await
            .expect("the fake succeeds by default");

        let blobs = fake.blobs_created.lock().unwrap();
        assert_eq!(blobs.len(), 3, "one blob per file: {blobs:?}");
        assert!(blobs.iter().any(|c| c == "contents-a"));
        assert!(blobs.iter().any(|c| c == "contents-b"));
        assert!(blobs.iter().any(|c| c == "contents-c"));

        let tree = fake.tree_entries.lock().unwrap().clone().expect("tree built");
        let paths: Vec<&str> = tree.iter().map(|(p, _)| p.as_str()).collect();
        assert_eq!(paths, vec!["Cargo.toml", "src/main.rs", "README.md"]);

        assert_eq!(outcome.repo, "my-repo");
        assert_eq!(outcome.default_branch, "main");
    }

    /// One commit for the whole push, never one per file — the entire point
    /// of using the Git Data API instead of the Contents API.
    #[tokio::test]
    async fn the_whole_kit_lands_as_a_single_commit() {
        let fake = FakeGitHubApi::default();
        let kit = kit_with(&[("a.txt", "1"), ("b.txt", "2"), ("c.txt", "3")]);

        push_kit(&fake, "tok", "repo", None, &kit).await.unwrap();

        assert_eq!(
            *fake.commit_calls.lock().unwrap(),
            1,
            "the whole kit must land as one commit, not one per file"
        );
        assert_eq!(*fake.ref_calls.lock().unwrap(), 1);
    }

    /// The commit carries no parents — the repository is empty, so this
    /// commit is its root, not a continuation of something GitHub seeded.
    #[tokio::test]
    async fn the_commit_has_no_parents() {
        let fake = FakeGitHubApi::default();
        let kit = kit_with(&[("a.txt", "1")]);
        push_kit(&fake, "tok", "repo", None, &kit).await.unwrap();
        assert!(fake.last_commit_had_no_parents.lock().unwrap().unwrap());
    }

    #[tokio::test]
    async fn a_repo_name_already_taken_is_reported_distinctly() {
        let fake = FakeGitHubApi::default();
        *fake.create_repo_result.lock().unwrap() = Some(Err(GitHubApiError::RepoNameTaken));
        let kit = kit_with(&[("a.txt", "1")]);

        let err = push_kit(&fake, "tok", "taken", None, &kit).await.unwrap_err();
        assert!(matches!(err, GitHubApiError::RepoNameTaken));
    }

    #[tokio::test]
    async fn a_rejected_token_surfaces_at_whichever_step_it_fails() {
        let fake = FakeGitHubApi::default();
        *fake.current_user_result.lock().unwrap() = Some(Err(GitHubApiError::TokenRejected));
        let kit = kit_with(&[("a.txt", "1")]);

        let err = push_kit(&fake, "tok", "repo", None, &kit).await.unwrap_err();
        assert!(matches!(err, GitHubApiError::TokenRejected));
        // Nothing past the failing step should have been attempted.
        assert!(fake.blobs_created.lock().unwrap().is_empty());
    }

    #[tokio::test]
    async fn a_scope_or_rate_limit_failure_partway_through_stops_the_push() {
        let fake = FakeGitHubApi::default();
        *fake.create_tree_error.lock().unwrap() = Some(GitHubApiError::RateLimited);
        let kit = kit_with(&[("a.txt", "1"), ("b.txt", "2")]);

        let err = push_kit(&fake, "tok", "repo", None, &kit).await.unwrap_err();
        assert!(matches!(err, GitHubApiError::RateLimited));
        // Blobs for both files were created before the tree step failed...
        assert_eq!(fake.blobs_created.lock().unwrap().len(), 2);
        // ...but no commit or ref followed a tree that never succeeded.
        assert_eq!(*fake.commit_calls.lock().unwrap(), 0);
        assert_eq!(*fake.ref_calls.lock().unwrap(), 0);
    }
}
